# Generated by Django 4.2.11 on 2025-02-25 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='year',
            field=models.PositiveIntegerField(default=2025),
        ),
        migrations.AlterUniqueTogether(
            name='member',
            unique_together={('phone', 'account_number', 'year')},
        ),
    ]
