# Generated by Django 4.2.11 on 2025-02-25 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0004_alter_member_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='year',
            field=models.PositiveIntegerField(default=2025),
        ),
    ]
